// <auto-generated />
namespace DrawNet.Lib.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Organize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Organize));
        
        string IMigrationMetadata.Id
        {
            get { return "201609180435381_Organize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
