// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DrawNet.Lib.TableInterfaces.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201603131226300_addedRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
