// <auto-generated />
namespace DrawNet.Lib.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class projectRecreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(projectRecreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201608260220349_project-Recreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
